#!/usr/bin/env bash
# Initialize local SQLite databases (default). Optionally start Postgres.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_DIR="${DATABASE_DIR:-$ROOT/data/db}"
mkdir -p "$DB_DIR"

PRODUCT_DB="$DB_DIR/cropmerge.sqlite"
VISION_DB="$DB_DIR/vision.sqlite"

echo "→ Product DB: $PRODUCT_DB"
sqlite3 "$PRODUCT_DB" < "$ROOT/tooling/db/sqlite-init-product.sql"
sqlite3 "$PRODUCT_DB" "PRAGMA journal_mode=WAL; SELECT 'product schema v' || value FROM schema_meta WHERE key='version';"

echo "→ Vision DB:  $VISION_DB"
sqlite3 "$VISION_DB" < "$ROOT/tooling/db/sqlite-init-vision.sql"
sqlite3 "$VISION_DB" "PRAGMA journal_mode=WAL; SELECT 'vision schema v' || value FROM schema_meta WHERE key='version';"

# Env snippet for apps
ENV_FILE="$DB_DIR/local.env"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-local-dbs.sh
DATABASE_DIR=$DB_DIR
DATABASE_URL=sqlite:///$PRODUCT_DB
VISION_DATABASE_URL=sqlite:///$VISION_DB
# Nuxt
NUXT_DATABASE_URL=sqlite:///$PRODUCT_DB
# Optional Postgres (after: docker compose up -d postgres)
# DATABASE_URL=postgresql://cropmerge:cropmerge@127.0.0.1:5432/cropmerge
# VISION_DATABASE_URL=postgresql://cropmerge:cropmerge@127.0.0.1:5432/cropmerge_vision
EOF

echo "→ Wrote $ENV_FILE"
echo ""
echo "SQLite ready. Source env:"
echo "  set -a; source $ENV_FILE; set +a"
echo ""
echo "Optional Postgres:"
echo "  docker compose up -d postgres"
echo "  docker compose --profile tools up -d adminer   # http://127.0.0.1:8088"
